from app.modules.simulator.programming.compiler.compiler_backend_base import (
    CompilerBackendBase,
)


class MicroPythonBackend(CompilerBackendBase):

    name = "micropython"

    def generate(
        self,
        ir,
    ):

        output = []

        self.line(
            "# Generated by Universal Automation Platform",
            output,
        )

        self.blank(output)

        for instruction in ir:

            opcode = instruction.get("opcode")

            self.line(

                f"# {opcode}",

                output,

            )

        return self.build(output)


micropython_backend = MicroPythonBackend()
